/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorPrincipal;
import Modelo.ListaEnlazada;
import Modelo.Producto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sofi
 */
public class PanelDatos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatos
     */
    ControladorPrincipal controladorPrincipal;
    private String[] etiquetas = {"Código", "Descripción", "Cantidad", "Precio", "Total"};
    private ListaEnlazada lista;

    public PanelDatos() {
        initComponents();
        estadoInicial();
    }

    public void estadoInicial() {
        jT_Codigo.setText("");
        jT_Cantidad.setText("");
        jT_descripcion.setText("");
        jT_precio.setText("");

        jb_registrar.setEnabled(true);

    }

    public void setLista(ListaEnlazada lista) {
        this.lista = lista;
    }

    public void escuchar(ControladorPrincipal controladorPrincipal) {
        jb_registrar.addActionListener(controladorPrincipal);
        jb_imprimir.addActionListener(controladorPrincipal);
        jb_revertir.addActionListener(controladorPrincipal);
//        jTa_Tabla.addMouseListener(controladorPrincipal);
    }

//    public void setTabla(String[][] datos, String[] titulos) {
//        DefaultTableModel model = null;
//        jTa_Tabla.setModel(new DefaultTableModel(datos, etiquetas));
//        jScrollPane1.setViewportView(jTa_Tabla);
//        model.fireTableDataChanged();
//        setVisible(true);
//    }

//    public String getIdFila() {
//        int fila = jTa_Tabla.getSelectedRow();
//        return String.valueOf(jTa_Tabla.getModel().getValueAt(fila, 0));
//    }
    
    public void setTabla(String[][] datos){
        DefaultTableModel model = new DefaultTableModel(datos, etiquetas);
        model.fireTableDataChanged();
        jTa_Tabla.setModel(model);
        
        //tblReporte.setModel(new DefaultTableModel(datos, etiquetas));
        //tblReporte.setModel(new DefaultTableModel());
        jScrollPane1.setViewportView(jTa_Tabla);
        jTa_Tabla.setVisible(true);
        
    }

    public double getTotal() {
        double precioTotal = 0;
        for (int fila = 0; fila < lista.getLongitud(); fila++) {
            precioTotal += (double) jTa_Tabla.getModel().getValueAt(fila, 4);
        }
        return precioTotal;
    }

    public String getTextCodigo() {
        return jT_Codigo.getText();
    }

    public String getTextDescripcion() {
        return jT_descripcion.getText();
    }

    public int getTextCantidad() {
        return Integer.parseInt(jT_Cantidad.getText());
    }

    public double getTextPrecio() {
        return Double.parseDouble(jT_precio.getText());
    }

    public void setTextCodigo(String codigo) {
        jT_Codigo.setText(codigo);
    }

    public void setTextDescripcion(String descripcion) {
        jT_descripcion.setText(descripcion);
    }

    public void setTextCantidad(int cantidad) {
        jT_Cantidad.setText(Integer.toString(cantidad));
    }

    public void setTextPrecio(double precio) {
        jT_precio.setText(String.valueOf(precio));
    }
     public void setJlPreciototal(double precioTotal){
        jlTotal.setText(String.valueOf(precioTotal));
    }
//
//    public Producto devolverInfo() {
//        return new Producto(Integer.parseInt(jT_Codigo.getText()), Integer.parseInt(jT_Cantidad.getText()), jT_descripcion.getText(), jT_precio.getText());
//    }

//    public void mostrarInfo(Producto producto) {
//        jT_Codigo.setText(Integer.toString(producto.getCodigo()));
//        jT_Cantidad.setText(Integer.toString(producto.getCantidad()));
//        jT_descripcion.setText(producto.getDescripcion());
//        jT_precio.setText(producto.getPrecio());
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_registrar = new javax.swing.JButton();
        jb_revertir = new javax.swing.JButton();
        jb_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTa_Tabla = new javax.swing.JTable();
        jT_Codigo = new javax.swing.JTextField();
        jT_descripcion = new javax.swing.JTextField();
        jT_Cantidad = new javax.swing.JTextField();
        jT_precio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();

        jb_registrar.setText("Registrar");

        jb_revertir.setText("Revertir");

        jb_imprimir.setText("Imprimir tiquete de compra");
        jb_imprimir.setActionCommand("Imprimir");

        jTa_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(jTa_Tabla);

        jLabel1.setText("Código");

        jLabel2.setText("Descripción");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Precio");

        jLabel5.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jT_precio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_Cantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_descripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jb_registrar)
                            .addGap(165, 165, 165)
                            .addComponent(jb_revertir)
                            .addGap(99, 99, 99)
                            .addComponent(jb_imprimir))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jT_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jT_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jT_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_registrar)
                    .addComponent(jb_revertir)
                    .addComponent(jb_imprimir))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Cantidad;
    private javax.swing.JTextField jT_Codigo;
    private javax.swing.JTextField jT_descripcion;
    private javax.swing.JTextField jT_precio;
    private javax.swing.JTable jTa_Tabla;
    private javax.swing.JButton jb_imprimir;
    private javax.swing.JButton jb_registrar;
    private javax.swing.JButton jb_revertir;
    private javax.swing.JLabel jlTotal;
    // End of variables declaration//GEN-END:variables
}
